app = "elliot-4200"
primary_region = 'arn'

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
